<a href="https://colab.research.google.com/github/e71828/Adaptive-Filter/blob/main/Chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import linalg
np.set_printoptions(precision=5, suppress=True)

In [ ]:
Ra = 1/4*np.asarray(linalg.toeplitz([4,3,2,1]))
pa = np.array([1/2, 3/8, 2/8, 1/8])
R = [Ra]
p = [pa]

Rb = np.asarray(linalg.toeplitz([1,0.8,0.64,0.512]))
pb = 1/4*np.array([0.4096, 0.512, 0.64, 0.8])
R.append(Rb)
p.append(pb)

Rc = 1/3*np.asarray(linalg.toeplitz([3, -2, 1]))
pc = np.array([-2,1,-1/2])
R.append(Rc)
p.append(pc)

for Ra,pa in zip(R,p):
    print(Ra)
    print('--------------')
    print(pa)
    print('--------------')

[[1.   0.75 0.5  0.25]
 [0.75 1.   0.75 0.5 ]
 [0.5  0.75 1.   0.75]
 [0.25 0.5  0.75 1.  ]]
--------------
[0.5   0.375 0.25  0.125]
--------------
[[1.    0.8   0.64  0.512]
 [0.8   1.    0.8   0.64 ]
 [0.64  0.8   1.    0.8  ]
 [0.512 0.64  0.8   1.   ]]
--------------
[0.1024 0.128  0.16   0.2   ]
--------------
[[ 1.      -0.66667  0.33333]
 [-0.66667  1.      -0.66667]
 [ 0.33333 -0.66667  1.     ]]
--------------
[-2.   1.  -0.5]
--------------


In [ ]:
## Wiener solution
w0 = []
for Ra,pa in zip(R,p):
    wa = linalg.inv(Ra)@pa
    w0.append(wa)
print(w0)

[array([0.5, 0. , 0. , 0. ]), array([0. , 0. , 0. , 0.2]), array([-2.4375, -0.75  , -0.1875])]


In [ ]:
lmax = []
for Ra in R:
    D,V = linalg.eig(Ra)
    print(D)
    print(max(D))
    lmax.append(max(D))

[2.77475+0.j 0.85355+0.j 0.22525+0.j 0.14645+0.j]
(2.774754878398196+0j)
[3.10318+0.j 0.55926+0.j 0.20882+0.j 0.12874+0.j]
(3.10318208944141+0j)
[2.12409+0.j 0.66667+0.j 0.20924+0.j]
(2.124093774423005+0j)


In [ ]:
def Gradient_Descent(pa, Ra, mu=1/5):
    w0 = np.zeros(pa.shape)
    g = -2*pa + 2*Ra @ w0
    while(linalg.norm(g)> 1e-5):
        w1 = w0 - mu*g
        w0 = w1
        g = -2*pa + 2*Ra @ w0
    return w0

In [ ]:
for Ra,pa in zip(R,p):
    w0 = Gradient_Descent(pa, Ra)
    print(w0)

[ 0.49999  0.00002 -0.00002  0.00001]
[ 0.00001 -0.00002  0.00002  0.19999]
[-2.43749 -0.74998 -0.18749]
